---
- name: Include mirror configs
  include_vars: mirrors.yml

- name: Create run-parts dir
  file:
    path: /var/mirror.d
    state: directory
    mode: 0755

- name: Create sync dirs
  file:
    path: "/srv/mirror/{{ item.name }}"
    state: directory
    mode: 0755
  with_items: "{{ mirrors }}"

- name: Install sync scripts
  template:
    src: reposync.j2
    dest: "/var/mirror.d/{{ item.name | regex_replace('\/', '_') }}"
    mode: 0755
  with_items: "{{ mirrors }}"

# add run-parts cron
- name: Add mirror run-parts cron entry
  cron:
    name: "sync mirrors"
    hour: "*/4"
    job: run-parts /var/mirror.d

# xiph mirror
- name: Add xiph user
  user:
    name: xiph

- name: Create xiph sync dir
  file:
    path: /srv/mirror/xiph
    state: directory
    mode: 0755
    owner: xiph

- name: Set up xiph ssh pubkey
  authorized_key:
    user: xiph
    state: present
    exclusive: True
    key: '{{ item }}'
    key_options: 'restrict,command="/usr/bin/rrsync /srv/mirror/xiph"'
  with_file:
    - xiph.pub

# userrepository mirror
- name: Add userrepository user
  user:
    name: userrepository

- name: Create userrepository sync dir
  file:
    path: /srv/mirror/userrepository
    state: directory
    mode: 0755
    owner: userrepository

- name: Set up userrepository ssh pubkey
  authorized_key:
    user: userrepository
    state: present
    exclusive: True
    key: '{{ item }}'
    key_options: 'restrict,command="/usr/bin/rrsync /srv/mirror/userrepository"'
  with_file:
    - userrepository.pub

