---
mirrors:
- name: armbian/apt
  source: rsync://rsync.armbian.com/apt
- name: blackarch
  source: rsync://blackarch.org/blackarch/
- name: draugeros/apt
  source: rsync://apt.draugeros.org/aptsync
- name: draugeros/download
  source: rsync://apt.draugeros.org/downloadsync
- name: garuda/repos
  source: builds.garudalinux.org::chaotic
- name: garuda/iso
  source: builds.garudalinux.org::iso
- name: heptapod
  source: rsync://download.heptapod.net/fosshost-mirrored
- name: ipfire
  source: rsync.ipfire.org::full
- name: kaos
  source: kaosx.tk::kaos
- name: linuxguides-os
  source: ams-01.rexum.space::files
- name: manjaro
  source: rsync://repo.manjaro.org/repos/
- name: serpentos/downloads
  source: rsync://download.serpentos.com/downloads
- name: serpentos/repository
  source: rsync://download.serpentos.com/repository
- name: ubuntudde
  source: rsync://repo.ubuntudde.com/ubuntudde/
- name: xiph
  source: rsync://ftp.osuosl.org/xiph/releases
